### PR TITLE
Fix mpi

### PR DESCRIPTION
**Pull request by kmuehlbauer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@conda-forge/h5py follow-up of #79 fixing dev mpi builds

**Comment by jakirkham** [comment]
cc @scopatz

**Comment by scopatz** [comment]
Thanks again @kmuehlbauer! This is still building from a github archive tarball.  I think this either needs to:

1. build from the 2.10 release tarball and include a patch that includes everything on master since then, or
2. use the [CFEP-05](https://github.com/conda-forge/cfep/blob/master/cfep-05.md) rules for prereleases and development releases

before I would be comfortable merging this.  At that point then I think we can/should mark the `2.11dev` packages as broken

**Comment by kmuehlbauer** [comment]
In https://github.com/h5py/h5py/pull/1652 it was suggested to use environment variables instead of CLI switch for this. Might be good to switch to it here too.

>  I think this either needs to:
> 
>     1. build from the 2.10 release tarball and include a patch that includes everything on master since then, or
> 
>     2. use the [CFEP-05](https://github.com/conda-forge/cfep/blob/master/cfep-05.md) rules for prereleases and development releases
> 
> 
> before I would be comfortable merging this

@scopatz Thanks for pointing that out. Could you please point me to one working conda feedstock which adheres to CFEP-05? And what should the source for point 2 be? PyPI? AFAICS there is no dev package in h5py github nor in PyPI. So this looks like only option one will work here. Is my assumption correct?

**Comment by scopatz** [comment]
I think matplotlib or matplotlib-base adheres to CFEP5, but yeah option 1 would be easier

**Comment by kmuehlbauer** [comment]
I've created a patch from last 2.10 release to current master, it's > 700kB. It just doesn't make sense IMHO to go this way, because maintainer's can't really check/review a patch of that size. Thoughts?

**Comment by scopatz** [comment]
I think it is way better than issuing future version numbers (that may never be released). I am open to suggestions here. CC @conda-forge/h5py

**Comment by kmuehlbauer** [comment]
@scopatz Maybe this took a bit too long, but that version thing wasn't clear to me. Thanks for clarifying.

**Comment by scopatz** [comment]
Yeah this recipe needs a lot of help ;)

**Pull request closed without merging**
