### PR TITLE
add pyreadline run requirement on windows

### PR DESCRIPTION
**Pull request by carlodri**
`pyreadline` is required for auto-completer to work on windows (addresses https://github.com/h5py/h5py/issues/971)

### CODE REVIEW

**Comment by carlodri** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
I think the failures are caused by NumPy 1.14's changes to structured dtypes. ( https://github.com/h5py/h5py/issues/969 ) Will probably need to upper bound the NumPy support to be anything less than 1.14.0.

**Comment by carlodri** [comment]
@jakirkham thanks for the tip, it seems to be working!

**Comment by jakirkham** [comment]
FYI @conda-forge/h5py, we are going to need to mark some packages as broken because of this.

**Comment by carlodri** [comment]
@conda-forge/h5py if you agree, this is ready to be merged

**Comment by jakirkham** [comment]
@tacaswell, could you please check this (and maybe merge) when you have a chance?

**Pull request merged**
