### PR TITLE
MNT: Re-rendered with conda-build 3.18.2, conda-smithy 3.3.4, and conda-forge-pinning 2019.05.31

### PR DESCRIPTION
**Pull request by ocefpaf**
Ping @rsignell-usgs

### CODE REVIEW

**Comment by scopatz** [comment]
I think there is an h5py release coming in a few days

**Comment by ocefpaf** [comment]
Let's leave the mpi issues for the stable release. These should be enough for now.

**Comment by scopatz** [comment]
@ocefpaf - please do not self-merge PRs where half the builds are broken without input from at least one other maintainer. This took me by surprise. And this is a development build that is not following CFEP-5

**Comment by ocefpaf** [comment]
As you know this is older than that [cfep-05](https://github.com/conda-forge/cfep/blob/master/cfep-05.md#backwards-compatibility) and another channel will disrupt users.

**Comment by rsignell-usgs** [comment]
I'll only add here that I greatly appreciate this dev release because it allowed previously working workflows broken by updates to function again!

**Comment by scopatz** [comment]
@ocefpaf @rsignell-usgs - we really should be fixing up broken builds though, rather than continuing to release them without review, especially when the CI is failing. I hope this makes sense. I am not asking that these be marked as broken, I just want this to be a community led development.

**Comment by scopatz** [comment]
@ocefpaf @rsignell-usgs - I understand the desire to have working environments with the most recent packages. Can one of you please put in a PR that passes CI and let another maintainer review & merge? This would be an meaningful demonstration of goodwill to me. Thanks! I would really appreciate it!

**Comment by scopatz** [comment]
Hey folks, please let me know what your intentions are here by the end-of-business UTC-5 tomorrow or I'll start putting in PRs to revert. I think we need to adhere to our own rules here and it is not OK for core members to break those just because they have the permissions to do so. Thanks for understanding.

**Comment by kmuehlbauer** [comment]
@scopatz To my understanding the mpi builds fail due to some problem with configuring. Not sure if this can be fixed here in the feedstock.

Short description of the problem:

The build is configured with `"${PYTHON}" setup.py configure $mpi_arg --hdf5="${PREFIX}"`, where $mpi_arg == `--mpi`.
When running it is checked for the env variable with `os.environ.get('HDF5_MPI') == "ON"` which results in `False` for our case.

Unfortunately in `finalize_options()` it is checked for `not None` and with `self.mpi=1` it in turn then raises the ValueError we see in the ci-logs:

```python
        # Merge environment options with command-line
        for setting, env_val in get_env_options().items():
            if env_val is not None:
                if getattr(self, setting) is not None:
                    raise ValueError(
                        f"Provide {setting} in command line or environment "
                        f"variable, not both."
                    )
```

Could we conclude that invoking with `--mpi` is currently broken in `h5py` master?

The fastest way to fix this feedstock's dev builds would be to fix the problem in h5py and update to the new commit hash here afterwards. Thoughts?

**Comment by scopatz** [comment]
Right, so we either shouldn't be building against master (preferred) or should not be building against mpi for the moment (less preferred, but still acceptable). If building against master, this should follow the CFEP-5 rules.

**Comment by kmuehlbauer** [comment]
@scopatz Please bear with me, I'm just testing this in #80. @conda-forge/h5py can close this down if patching this is not the correct way of doing.

**Comment by scopatz** [comment]
Patching is exactly the right way to fix this, thanks for taking a look @kmuehlbauer

**Pull request merged**
