### PR TITLE
HDF5 1.10.5

### PR DESCRIPTION
**Pull request by ax3l**
Resubmitting @bgruening's #58 with proper upstream patch by @tacaswell

https://github.com/h5py/h5py/pull/1186

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase @conda-forge-admin, please rerender in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
@conda-forge/h5py only a Python 2.7 package conflict on windows left :) any idea?

**Comment by ocefpaf** [comment]
> @conda-forge/h5py only a Python 2.7 package conflict on windows left :) any idea?

You have to skip that. We have `hdf5 1.10.5` for `vc9`. See https://github.com/conda-forge/hdf5-feedstock/blob/master/recipe/meta.yaml#L37

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
@conda-forge/h5py okay, ready for merge now :)

**Pull request merged**
