### PR TITLE
Arch: Add aarch64 and ppc64le

### PR DESCRIPTION
**Pull request by ax3l**
Add builds for these new platforms.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by tacaswell** [comment]
For linux linux_aarch64_mpimpichpython2.7

```
failed
failed to parse packages from exception: The following specifications were found to be incompatible with each other:



Package six conflicts for:
unittest2 -> six[version='>=1.4']
…Package openssl conflicts for:
python[version='>=2.7,<2.8.0a0'] -> openssl[version='>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a']
Package openmpi conflicts for:
mpi4py -> openmpi[version='>=4.0,<4.1.0a0']
Package tk conflicts for:
```

It looks like python2 is missing some some build deps?

Can we just drop the python2 builds on arm + mpi?

**Comment by ax3l** [comment]
Sure, no problem to skip ARM+Python 2+MPI combos.

But looks to me like PPC64 is failing as well, for all python versions. Do you understand what is going on there?

**Comment by ax3l** [comment]
@tacaswell dependencies are updated, I rebased and rerendered this PR :)

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
@tacaswell hooray, h5py on ppc64le and aarch64 builds are ready for merge! :)

**Review by tacaswell — APPROVED** [review]
holding off on merging as I'm not sure if there is any extra protocol around adding new architectures.

**Review by jakirkham — APPROVED** [review]

**Comment by ax3l** [comment]
ping @scopatz @ocefpaf @minrk arch-migration for h5py ready for merge :)

**Pull request merged**
