### PR TITLE
h5py v3.1.0 update

### PR DESCRIPTION
**Pull request by Anthchirp**
Test builds with patched up recipe.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Anthchirp** [comment]
@conda-forge/h5py so.. fundamentally this builds

However, `h5py` has made a conscious choice to [require an exact specific version of numpy in the environment for building](https://github.com/h5py/h5py/blob/3.0.0/setup.py#L28-L52), the exact version depending on the version of python:

python | numpy
--- | ---
3.6 | ==1.12.*
3.7 | == 1.14.5
3.8 | == 1.17.5
3.9 | == 1.19.3

One consequence of this choice is that we can't just use the regular numpy pinning mechanism, as `setup.py` will then just try (and fail) to `pip install` the exact 'correct' numpy version from the table instead.

So I've taken the [astropy approach](https://github.com/conda-forge/astropy-feedstock/blob/d3cf9214b647d36e8932346ca60c6fb9748a6986/recipe/meta.yaml#L30-L48) in this pull request.
This turns out to work for Linux 3.6 up to 3.8. Linux 3.9 will fail, as we don't have numpy 1.19.3 built yet (which is why _currently_ the recipe skips 3.9).

MacOS builds are a different story. There is no 1.12.* compatible version of numpy in combination with the HDF5 libraries. The working minimum versions above the minimums given above should be approximately:

python | numpy
--- | ---
3.6 | 1.14.6
3.7 | 1.14.6
3.8 | 1.18.1
3.9 | (untested)

And the arm64 build of course is also lacking many of the older numpy versions and combinations.

So I am thinking we should probably take the alternative approach here: patch out the hard `h5py` setup build requirement and use the normal pinning mechanism. Given that h5py 3.0 does say that it should _fundamentally_ work with numpy 1.12 on Python 3.6, I don't see why it wouldn't also work with numpy 1.12 on Python 3.9.

Anyway, I thought at this stage I'd ask for your input.


Other changes made:
* removed Python 2.7 references from the recipe
* updated dependencies (-six, +cached-property; test dependency +pytest-mpi)
* added `pip check` test

**Comment by aragilar** [comment]
@Anthchirp The numpy versions are the minimum version that a) numpy says is supported on that python version and b) have wheels on PyPI. Feel free to adjust HDF5 and numpy version used as needed. Cython you likely want to use the version we use or later.

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by Anthchirp** [comment]
Thanks @aragilar.

@conda-forge/h5py ready for review

(The build failures on the final and the previous commit are transient network connection issues)

**Comment by kmuehlbauer** [comment]
@Anthchirp It might be worth skipping 3.0 and directly go with 3.1, see https://docs.h5py.org/en/latest/whatsnew/3.1.html.

**Comment by Anthchirp** [comment]
Done.

Do we prefer downloading sources from github or pypi?

**Comment by ocefpaf** [comment]
> Do we prefer downloading sources from github or pypi?

That is a good question and the short answer is PyPI. The long answer, it depends. I would love to use anything closer to the source, like GH, but the checksum on releases change, people don't push "clean tarbell's", etc. Forcing us to use PyPI. However, sometimes the wrist on PyPI  is missing tests, metadata files, license, etc. Forcing us to use GH.

**Pull request merged**
