### PR TITLE
parallel builds

### LINKED ISSUE #44: h5py parallel build
The conda-forge hdf5 now offers a parallel build (conda-forge/hdf5-feedstock#90). I'd really like to see this channel offer a parallel h5py build as well. What can I do to help get this going?

### PR DESCRIPTION
**Pull request by minrk**
This adds mpi to the build matrix

This won't work quite yet, mainly for two reasons:

1. mpi builds have only been added for hdf5 1.10.4, but conda-forge-pinning still has 1.10.3
2. conda/conda-build#3264 causes runtime dependencies to lose build strings.

above has been resolved.

I'm investigating a way to workaround 2., but I haven't been able to find a way to override pin_run_as_build to the point that it's *removed*. I can change the values, but I cannot change the fact that hdf5 has pin-run-as-build. The only workaround I can think of other than waiting for a conda-build release is to switch hdf5 to using run_exports (it's already doing this for the mpi builds) and then removing hdf5 from pin_run_as_build in conda-forge-pinning altogether. Does that sound like a reasonable plan?

todo:

- [x] bump hdf5 pinning to 1.10.4 in conda-forge-pinning
- [x] (maybe?) add run_exports to hdf5 and remove hdf5 from pin_run_as_build
- [x] add mpi tests
- [x] resolve build numbers vs features in https://github.com/conda-forge/hdf5-feedstock/pull/98

closes #44

### CODE REVIEW

**Comment by minrk** [comment]
Something weird is happening in the solver, picking old mpi4py 2.0 from defaults. Presumably due to a conflict somewhere. Investigating...

**Comment by minrk** [comment]
I think conda-build cannot resolve build strings in host requirements correctly until https://github.com/conda/conda-build/pull/3264 is released.

**Comment by minrk** [comment]
All mpi builds appear to be succeeding.

**Comment by ocefpaf** [comment]
Thanks @minrk!

@tacaswell can you take a look at this? LGTM but I would like your approval before merging.

**Comment by minrk** [comment]
@ocefpaf thanks! I think 
https://github.com/conda-forge/hdf5-feedstock/pull/98 should be resolved first (I think it's ready to go, but a second opinion would be helpful). This PR matches that one right now, so if they are both approved, they can go in.

**Comment by ocefpaf** [comment]
> [conda-forge/hdf5-feedstock#98](https://github.com/conda-forge/hdf5-feedstock/pull/98) should be resolved first (I think it's ready to go, but a second opinion would be helpful).

Done.

> This PR matches that one right now, so if they are both approved, they can go in.

Ping @conda-forge/h5py team.

**Comment by rabernat** [comment]
👍 from a user who would like to conda install parallel h5py!

**Comment by rabernat** [comment]
Just a 🏓 from a user who is eager to use this! Thanks to all the volunteers working on this effort.

**Comment by ocefpaf** [comment]
Let's merge this and, if the @conda-forge/h5py team find any issues, we can pull the packages.

**Pull request merged**
