### PR TITLE
MNT: rerender

### LINKED ISSUE #34: @conda-forge-admin, please rerender
@conda-forge-admin, please rerender

(Based on my previous experience, it will be necessary to comment an extra time for the rerender to actually get triggered.)

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #34.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #34

### CODE REVIEW

**Comment by pkgw** [comment]
I triggered this to get a rebuild against the new `hdf5` pinning.

**Comment by jakirkham** [comment]
According to [this comment]( https://github.com/conda-forge/h5py-feedstock/pull/33#issuecomment-423360989 ), there are test failures with this version of HDF5.

@conda-forge/core, it seems like we bumped the HDF5 version too quickly. Would it be possible to revert to an older version of HDF5 like 1.10.2?

**Comment by scopatz** [comment]
Yeah feel free to drop the pinning

**Comment by ocefpaf** [comment]
Done in #36

**Pull request closed without merging**
