### PR TITLE
Rebuild for Python 3.13

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
@conda-forge/h5py Ready for a merge!

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Comment by tkelman** [comment]
Thought the bot would get to this eventually, is this bot error a bug somewhere?
```
bot error (
[bot CI job](https://github.com/regro/cf-scripts/actions/runs/11377581203)
): main:
Traceback (most recent call last):
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 721, in _run_migrator_on_feedstock_branch
    migrator_uid, pr_json = run_with_tmpdir(
                            ^^^^^^^^^^^^^^^^
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 445, in run_with_tmpdir
    return run(
           ^^^^
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 547, in run
    rerender_info = _run_rerender(
                    ^^^^^^^^^^^^^^
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 252, in _run_rerender
    rerender_msg = rerender_feedstock(str(context.local_clone_dir), timeout=900)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/rerender_feedstock.py", line 24, in rerender_feedstock
    return _rerender(feedstock_dir, timeout=timeout, use_container=use_container)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/conda_forge_feedstock_ops/rerender.py", line 48, in rerender
    return rerender_containerized(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/conda_forge_feedstock_ops/rerender.py", line 116, in rerender_containerized
    if data["commit_message"] is not None and data["patch"] is not None:
                                              ~~~~^^^^^^^^^
KeyError: 'patch'
```
https://github.com/regro/cf-scripts/actions/runs/11377581203

**Comment by xhochy** [comment]
Yes, looks like we have a general bug in the code as this is popping up in a lot of migrations.

**Pull request merged**
