### PR TITLE
Add license_file metadata.

### PR DESCRIPTION
**Pull request by tylere**
Add license_file metadata so that the license file is installed as part of the package.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@tylere consider adding yourself as a maintainer too :wink:

**Comment by jakirkham** [comment]
Please bump the build number too.

**Comment by tylere** [comment]
Done.

**Comment by tylere** [comment]
Considered, but I feel I need some more experience with conda-forge before
taking that step.

**Comment by ocefpaf** [comment]
> Considered, but I feel I need some more experience with conda-forge before
> taking that step.

Fair enough. But a PR like that is more advanced than most of what we
expect from maintainers ;-)

**Comment by jakirkham** [comment]
Thanks @tylere.

**Pull request merged**
