### PR TITLE
Py36

### PR DESCRIPTION
**Pull request by ocefpaf**

### CODE REVIEW

**Comment by jakirkham** [comment]
Please re-render with `conda-smithy` version `1.7.0`. I do not want dev re-renderings with `conda-smithy` going out. Also please do not self-merge I'd like to verify the changes when completed. Thanks.

**Comment by ocefpaf** [comment]
> Please re-render with `conda-smithy` version `1.7.0`. I do not want dev re-renderings with `conda-smithy` going out. Also please do not self-merge I'd like to verify the changes when completed. Thanks.

This is not conda-smithy dev. This is auto that by-passes all the issues with `.condarc`

> Also please do not self-merge

Merge fast it is needed for a lot of other projects. I would encourage you do to the same. Your self-merges in conda-`smithy` gave birth to auto.

**Comment by ocefpaf** [comment]
> I do not want dev re-renderings with conda-smithy going out

Also why you do not want that? You self-merge changes there and issues releases without consulting or waiting anyone? What is the difference if I just create a release with this changes? Be reasonable!

**Comment by jakirkham** [comment]
My concerns are as follows. First there were some issues with the previous re-rendering of `matplotlib`, which I wanted to make sure were not encountered here. Second re-renderings that differ from those generated the bot will just increase the re-rendering churn and eat up more resources. Hope that makes sense.

**Comment by ocefpaf** [comment]
No it dos not as we are already suffering that due to the many changes you make constantly, and self-merge, in conda-smithy and the slowness to move to conda-build 2 forcing us to hack that into the feedstock.

Not to mentioned that the original design of conda-forge was to allow for some manual tweaks and and just ignore bot rendering when they did not make sense instead of merging them like a bot.

Either way defaults got this so the rest of conda-forge is not going to be kept outdated b/c of this feestock you are holding back.

**Comment by ocefpaf** [comment]
Superseded by #18 (Ouch! How many re-renders PRs are needed here!!!)

**Pull request closed without merging**
