### PR TITLE
MNT: version bump for 2.7.0

### PR DESCRIPTION
**Pull request by tacaswell**
- bump to 2.7.0
 - switched to sha256 for checksum
 - none of the patches apply correctly.  The changes to windows build upstream are currently tested on appveyor so keep those over the patch.  The other two patches have been dealt with upstream.

### CODE REVIEW

**Comment by tacaswell** [comment]
attn @aragilar can you look at the windows failures?

They are failing with

```
======================================================================
ERROR: test_load_from_image (h5py.tests.old.test_file_image.TestFileImage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\bld\h5py_1489867335307\_t_env\lib\site-packages\h5py\tests\old\test_file_image.py", line 20, in test_load_from_image
    fapl.set_file_image(image)
AttributeError: 'h5py.h5p.PropFAID' object has no attribute 'set_file_image'
----------------------------------------------------------------------
Ran 439 tests in 0.750s

```

Did you see this when you were setting up appveyor for h5py CI?

**Comment by aragilar** [comment]
It's failing because the version h5py was targeting was 1.8.4, whereas conda-forge is using 1.8.17.
Either HDF5_VERSION=1.8.17 needs to be set in the environment, or --hdf5-version=1.8.17 passed to setup.py (whichever is easier for the build system to handle).

**Comment by tacaswell** [comment]
@pitrou @jakirkham This is ready to go!

**Comment by jakirkham** [comment]
Could you please reset the build number? Otherwise LGTM.

**Comment by tacaswell** [comment]
build number reset.

**Comment by jakirkham** [comment]
Thanks @tacaswell.

**Pull request merged**
