### PR TITLE
Force rebuild against hdf5 1.10.3

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
Strange: the builds are not pulling in hdf5 1.10.3 even though those packages [exist](https://anaconda.org/conda-forge/hdf5/files).

Any thoughts as to why this is happening?

**Comment by kmuehlbauer** [comment]
@tschoonj Because the whole stack is pinned to `1.10.2` (https://github.com/conda-forge/h5py-feedstock/blob/b750cbcbe184b01bd5b9f240349ec32279ddee54/.ci_support/linux_python3.6.yaml#L4)

**Comment by tschoonj** [comment]
I see... so this PR is pointless? What needs to happen to get the whole stack using 1.10.3?

**Comment by kmuehlbauer** [comment]
> I see... so this PR is pointless? 

Yes, so to say...

> What needs to happen to get the whole stack using 1.10.3?

The global stack pinning needs to be adjusted [here](https://github.com/conda-forge/conda-forge-pinning-feedstock) and then the stack has to be rebuilt for all dependencies. 

See also the docs on pinning [here](https://conda-forge.org/docs/meta.html#pinning-packages).

**Comment by tschoonj** [comment]
Ok thanks for the info

**Comment by tacaswell** [comment]
@tschoonj Is there something you need in 1.10.3?  There are test failures with 1.10.3 that we do not understand yet (see https://github.com/h5py/h5py/issues/1088).

**Comment by tschoonj** [comment]
Not really, just thought it was strange that `h5py` wasn't using hdf5 1.10.3 yet.

Anyway I had conda-forge pinning [updated](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/122) to use hdf5 1.10.3

**Pull request closed without merging**
