### PR TITLE
Add patch for issue #775 (py3 issues)

### PR DESCRIPTION
**Pull request by pitrou**
See https://github.com/h5py/h5py/issues/775

### CODE REVIEW

**Comment by pitrou** [comment]
Weird errors on Circle-CI and AppVeyor that don't seem related to this PR...

**Comment by pitrou** [comment]
Ok, I've now "rerendered" the recipe (why doesn't the linter catch this?).

**Comment by pitrou** [comment]
@jakirkham

**Comment by ocefpaf** [comment]
@pitrou do you want to add yourself as a maintainer here?

**Comment by pitrou** [comment]
> @pitrou do you want to add yourself as a maintainer here?

Well, why not.

**Pull request merged**
