### PR TITLE
h5py v3.6.0 (redux)

### PR DESCRIPTION
**Pull request by h-vetinari**
Picking up changes from #106 & #105, because they've grown conflicts after #104.

Closes #106 
Closes #105 
Closes #102

### CODE REVIEW

**Comment by h-vetinari** [comment]
So running the test suite for the mpi-builds (non-`nompi`) runs into three errors on unix with @MarDiehl's proposed changes:
```
=========================== short test summary info ============================
FAILED tests/test_file.py::TestPageBuffering::test_actual_pbs - OSError: Unab...
FAILED tests/test_file.py::TestPageBuffering::test_check_page_buf_size - OSEr...
FAILED tests/test_file.py::TestPageBuffering::test_only_with_page_strategy - ...
================== 3 failed, 668 passed, 24 skipped in 8.54s ===================
```

all due to `OSError: Unable to open file (page buffering is disabled for parallel)`. It might be that the upstream test suite should not even attempt to run these tests when run in parallel?

**Comment by MarDiehl** [comment]
@h-vetinari: I believe it is impossible to run the tests via `import h5py, sys; sys.exit(h5py.run_tests()` together with pytest-mpi. Pytest needs to be invoked directly, i.e. with `mpiexec -np 2 python -m pytest --with-mpi`. This searches the current directory for the tests. I failed to figure out where conda stores the source code to get this working.

**Comment by h-vetinari** [comment]
> I believe it is impossible to run the tests via `import h5py, sys; sys.exit(h5py.run_tests()` together with pytest-mpi

Well, I don't know the h5py codebase, but `h5py.run_tests` directly [calls](https://github.com/h5py/h5py/blob/3.6.0/h5py/tests/__init__.py#L11) pytest.

I also kept the `mpiexec -np 1` that you had in #105 - it's being inserted before the call to python. Do you mean it must be `-np 2`?

Finally, in an ideal world, the test suite should be smart enough to execute or skip relevant tests based on the availability of mpi. But if that's not possible for some reason, we can of course rewrite the invocation of it so that we pass all the relevant information to the runner.

**Comment by h-vetinari** [comment]
> This searches the current directory for the tests. I failed to figure out where conda stores the source code to get this working.

Right now, we're calling the tests as they are present in the packaged library, but we _can_ pass through the sources for tests etc. with `source_files:` if we want to.

**Comment by h-vetinari** [comment]
Seems the tests aren't built for running from source - due to relative imports, this runs into some funky import errors.

**Comment by MarDiehl** [comment]
> I also kept the `mpiexec -np 1` that you had in #105 - it's being inserted before the call to python. Do you mean it must be `-np 2`?
> 
the '2' was a copy and paste error, as far as I remember '1' would also work.

Edit: I will check on my computer to figure out what I did to get it working

**Comment by h-vetinari** [comment]
So I think the function signature of `h5py.run_tests` is flexible enough to allow us to pass in pretty much arbitrary arguments. Certainly `--with-mpi` seems to have made an effect, but now tests are segfaulting, apparently.

One question I have is how this change in the testing is related to the version upgrade? How about we remove these changes here and take care of them in a separate PR?

In any case, I'll invite you as a collaborator on my fork, then you can push into this PR - I won't have time for the next few hours.

**Comment by MarDiehl** [comment]
I installed h5py manually and the following steps (taken from https://github.com/archlinux/svntogit-community/blob/packages/python-h5py-openmpi/trunk/PKGBUILD) work on my system.

```
tar -xf h5py-3.6.0.tar.gz
cd h5py-3.6.0
export CC=mpicc
HDF5_MPI="ON" H5PY_SYSTEM_LZF=1 python setup.py build
cd build/lib.linux-x86_64-3.9
export PYTHONPATH=$PWD
mpiexec -np 1 python -m pytest --with-mpi # python -m pytest --with-mpi works also
```
I think it should be possible to do something similar with conda, but I don't have it installed.

**Comment by tacaswell** [comment]
superseded by  #109

**Pull request closed without merging**
